# Generated by Django 4.2.5 on 2023-09-10 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemType', models.CharField(choices=[('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphones', 'Headphones'), ('USB Drive', 'USB Drive'), ('Laptop Charger', 'Laptop Charger'), ('HDMI Cable', 'HDMI Cable'), ('Ethernet Cable', 'Ethernet Cable'), ('Wireless Adapter', 'Wireless Adapter'), ('Web Camera', 'Web Camera'), ('Microphone', 'Microphone'), ('Power Bank', 'Power Bank'), ('Phone Charger', 'Phone Charger')], default='Mouse', max_length=25, verbose_name='Type')),
                ('itemDescription', models.TextField(default='', help_text='Insert a brief product description', max_length=400, verbose_name='Description')),
                ('itemPrice', models.DecimalField(decimal_places=2, default=0.5, max_digits=4, verbose_name='Price')),
                ('itemQuantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantity')),
                ('itemImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hItemType', models.CharField(choices=[], max_length=25, verbose_name='Type')),
                ('hItemPrice', models.DecimalField(decimal_places=2, default=0.5, max_digits=4, verbose_name='Price')),
                ('purchaseTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchase Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
