# Generated by Django 4.2.5 on 2024-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Price'),
        ),
    ]
