# Generated by Django 5.0.2 on 2024-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_itemprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='hItemType',
            field=models.CharField(choices=[('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Headphones', 'Headphones'), ('USB Drive', 'USB Drive'), ('Laptop Charger', 'Laptop Charger'), ('HDMI Cable', 'HDMI Cable'), ('Ethernet Cable', 'Ethernet Cable'), ('Wireless Adapter', 'Wireless Adapter'), ('Web Camera', 'Web Camera'), ('Microphone', 'Microphone'), ('Power Bank', 'Power Bank'), ('Phone Charger', 'Phone Charger')], max_length=25, verbose_name='Type'),
        ),
    ]
